#!/bin/bash

# This script must be run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)" 1>&2
   exit 1
fi

# Install GIT version control
apt-get install git

# Install Emacs editor
apt-get install emacs23
